---
deployment:
  tasks:
    - source /home/suckerpu/nodevenv/repositories/danielamsel/16/bin/activate && cd /home/suckerpu/repositories/danielamsel
    - npm install
    - npm run build-prod
    - touch -m tmp/restart.txt